### ISSUE TITLE
Embedding the network into the filename

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/contracts#26]
Referring to https://github.com/alpha-wallet/contracts/commit/c2bb6f2cab7eaeab24b9d8cbb8602771e34f40a9#diff-04c6e90faac2675aa89e2176d2eec7d8R27

I was under the impression that @JamesSmartCell meant to replace the on-device filename

`mainnet/0xA66A3F08068174e8F005112A8b2c7A507a822335.xml`

with:

`mainnet-0xA66A3F08068174e8F005112A8b2c7A507a822335.xml`

(or `1-0xA66A3F08068174e8F005112A8b2c7A507a822335.xml`)

**Comment by JamesSmartCell** [comment]
there's no need to put mainnet-0xabcabcabc....xml. This just complicates the code and introduces problems for later.

On Android I just use the contract address then .xml.

EG 0xA66A3F08068174e8F005112A8b2c7A507a822335.xml

Is the DMZ app using an unnecessarily complex system? Remember that there's never a contract address collision between mainnet and testnets.

The network ID is within the XML. No need to duplicate this outside. Also this breaks what we discussed on the phone a couple of days ago - ie that you can have multiple contracts and multiple testnets within the same XML.

Best to keep it simple! Otherwise you're creating problems.

**Comment by hboon** [comment]
Ah, I misunderstood. Thanks.
